name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [ published ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      #Publicamos en GithubPackages
      - uses: actions/checkout@v3
      #Publicamos en GithubPackages
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Substituted with the value stored in the referenced secret
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # Env var that holds the key's passphrase
      - name: Publish to GitHub Packages
        run: mmvn --batch-mode deploy -P Github -s $GITHUB_WORKSPACE/.github/workflows/Publish/settingsGitHub.xml -X
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGN_KEY_PASS }}
          GITHUB_TOKEN: ${{ secrets.DEPLOY_ACTIONS_GITHUB }}
