name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [ published ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      #Publicamos en GithubPackages
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      #import the secret key
      - name: Set up Apache Maven GitHub
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_USERNAME
          server-password: GITHUB_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Substituted with the value stored in the referenced secret
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # Env var that holds the key's passphrase
          cache: 'maven'
      - name: Publish to GitHub Packages
        #run: mvn --batch-mode deploy -P Github -Darguments=-Dgpg.passphrase=${{ secrets.SIGN_KEY_PASS }} -s $GITHUB_WORKSPACE/.github/workflows/Publish/settingsGitHub.xml -X
        run: mvn --batch-mode deploy -P Github -Darguments=-Dgpg.passphrase=${{ secrets.SIGN_KEY_PASS }} -X
        env:
          GITHUB_USERNAME: ${{ secrets.USER_NAME }}
          GITHUB_PASSWORD: ${{ secrets.ACCESS_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGN_KEY_PASS }}
          GITHUB_TOKEN: ${{ secrets.DEPLOY_ACTIONS_GITHUB }}
