name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [ published ]
permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      #Publicamos en GithubPackages
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v3.6.0
      #Corremos los servicios de Docker
      - name: Deploy Services DataBases
        run: docker compose -f ./compose.yaml up -d
      - name: Set up JDK 21
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      #Limpiamos la cache de Maven
      - name: Limpiamos la cache de Maven
        run: mvn -B clean
        #Esperamos la inicialización de los servicios de docker
      - name: Espera Mientras Inician los Servicios de Docker
        run: sleep 10s
      #import the secret key
      - name: Set up Apache Maven GitHub
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_USERNAME
          server-password: GITHUB_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Substituted with the value stored in the referenced secret
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # Env var that holds the key's passphrase
          cache: 'maven'
      - name: Publish to GitHub Packages
        #run: mvn --batch-mode deploy -P Github -Darguments=-Dgpg.passphrase=${{ secrets.SIGN_KEY_PASS }} -s $GITHUB_WORKSPACE/.github/workflows/Publish/settingsGitHub.xml -X
        run: mvn --batch-mode deploy -P Github -Darguments=-Dgpg.passphrase=${{ secrets.SIGN_KEY_PASS }} -X
        env:
          GITHUB_USERNAME: ${{ secrets.USER_NAME }}
          GITHUB_PASSWORD: ${{ secrets.ACCESS_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGN_KEY_PASS }}
          GITHUB_TOKEN: ${{ secrets.DEPLOY_ACTIONS_GITHUB }}
