name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [ published ]
permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      #Publicamos en GithubPackages
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up JDK 17
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      #import the secret key
      - name: Set up Apache Maven GitHub
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_USERNAME
          server-password: GITHUB_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Substituted with the value stored in the referenced secret
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # Env var that holds the key's passphrase
          cache: 'maven'
      - name: Publish to GitHub Packages
        #run: mvn --batch-mode deploy -P Github -Darguments=-Dgpg.passphrase=${{ secrets.SIGN_KEY_PASS }} -s $GITHUB_WORKSPACE/.github/workflows/Publish/settingsGitHub.xml -X
        run: mvn --batch-mode deploy -P Github -Darguments=-Dgpg.passphrase=${{ secrets.SIGN_KEY_PASS }} -X
        env:
          GITHUB_USERNAME: ${{ secrets.USER_NAME }}
          GITHUB_PASSWORD: ${{ secrets.ACCESS_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGN_KEY_PASS }}
          GITHUB_TOKEN: ${{ secrets.DEPLOY_ACTIONS_GITHUB }}
